build:
    environment:
        php: '7.1.12'

    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
            environment:
                node:
                    version: 6.0.0
        tests: true
    tests:
        before:
            - bash .travis/install-wp-tests.sh wordpress_test root '' localhost latest
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'

filter:
    excluded_paths:
        - 'tests/*'
        - '*.min.js'
        - 'gulpfile.js'
    dependency_paths:
        - wordpress/

checks:
    php:
        phpunit_assertions: true
        return_doc_comment_if_not_inferrable: true
        return_doc_comments: true
        simplify_boolean_return: true
        parameter_doc_comments: true
        no_goto: true
        fix_line_ending: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        param_doc_comment_if_not_inferrable: true
    javascript: true
